USE DATABASE "attribution";
USE SCHEMA "public";

DROP MATERIALIZED VIEW "attribution"."public"."mv_share_of_model";
DROP MATERIALIZED VIEW "attribution"."public"."mv_won_revenue_by_account";
DROP MATERIALIZED VIEW "attribution"."public"."mv_channel_touch_distribution";
DROP MATERIALIZED VIEW "attribution"."public"."mv_funnel_by_category";
DROP MATERIALIZED VIEW "attribution"."public"."mv_spend_by_channel";
DROP STREAM "attribution"."public"."funnel_events";
DROP STREAM "attribution"."public"."spend";
DROP STREAM "attribution"."public"."conversions";
DROP STREAM "attribution"."public"."touchpoints";
DROP CHANGELOG "attribution"."public"."web_identity_map";
DROP STREAM "attribution"."public"."web_resolved";
DROP CHANGELOG "attribution"."public"."sf_contacts";
DROP CHANGELOG "attribution"."public"."sf_accounts";
DROP STREAM "attribution"."public"."sf_opportunities";
DROP STREAM "attribution"."public"."ga4_events";
DROP STREAM "attribution"."public"."hubspot_events";
DROP STREAM "attribution"."public"."outreach_activity";
DROP STREAM "attribution"."public"."linkedin_ads";
DROP STREAM "attribution"."public"."google_ads";
DROP STREAM "attribution"."public"."channel_cost";
DROP STREAM "attribution"."public"."share_of_model";
