#!/usr/bin/env bash
# Edit the values in the block below, then run:  bash scripts/make_settings.sh
# It writes config/settings.yaml (gitignored) — the agent, datagen, and dashboard
# all read their config + secrets from there, so you set them once. Re-running
# overwrites it (a .bak is kept). Merges over config/settings.example.yaml, so
# topic names / guardrails / etc. come from there; you only fill in the secrets.
set -euo pipefail
cd "$(dirname "$0")/.."

# ============================ EDIT THESE ============================
KAFKA_BOOTSTRAP="PASTE_WARPSTREAM_BOOTSTRAP:9092"
KAFKA_KEY="PASTE_WARPSTREAM_SASL_USERNAME"
KAFKA_SECRET="PASTE_WARPSTREAM_SASL_PASSWORD"
KAFKA_CA="config/warpstream-ca.pem"   # path where you saved the WarpStream CA (PEM)
DS_MCP_ENDPOINT="https://api-mizaz8.deltastream.io/mcp/v1"
DS_API_TOKEN="PASTE_DELTASTREAM_API_TOKEN"
ANTHROPIC_KEY="PASTE_ANTHROPIC_API_KEY"
# ===================================================================

OUT="config/settings.yaml"
if [ -f "$OUT" ]; then cp "$OUT" "$OUT.bak"; echo "backed up existing -> $OUT.bak"; fi

cat > "$OUT" <<YAML
# Generated by scripts/make_settings.sh — gitignored, holds local secrets.
kafka:
  bootstrap_servers: "$KAFKA_BOOTSTRAP"
  sasl_username: "$KAFKA_KEY"
  sasl_password: "$KAFKA_SECRET"
  ssl_ca_location: "$KAFKA_CA"

deltastream:
  mcp_endpoint: "$DS_MCP_ENDPOINT"
  api_token: "$DS_API_TOKEN"

agent:
  anthropic_api_key: "$ANTHROPIC_KEY"
YAML

echo "wrote $OUT"
echo "note: dsql/deploy still read the token from the env — also run:"
echo "      export DS_TOKEN=\"$DS_API_TOKEN\""
